Algoritmo "Função Interna"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2022
Var
logaritmo, numero : real

Inicio
escreval ("Digite um número para calcular seu logaritmo:")
leia (numero)

logaritmo <- log (numero)

escreval("O log do número digitado é ", logaritmo)

Fimalgoritmo